#!/bin/bash
set -e

source /usr/local/bin/toolchain.sh

LIST_MODE=0
TC_ARGS=()

for arg in "$@"; do
    case "$arg" in
        -l|--list) LIST_MODE=1 ;;
        *)
            TC_ARGS+=("$arg")
            ;;
    esac
done

if [ "$LIST_MODE" = "1" ]; then
    exec /usr/local/bin/list-toolchains
fi

download_single() {
    local norm
    norm=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    case "$norm" in
        tc1) download_tc1 ;;
        tc2) download_tc2 ;;
        tc3) download_tc3 ;;
        tc4) download_tc4 ;;
        *)   echo "[k230] error: unknown toolchain '$1'" >&2; return 1 ;;
    esac
}

if [ ${#TC_ARGS[@]} -eq 0 ]; then
    echo "[k230] downloading enabled toolchains..."
    [ "${ENABLE_TC1:-1}" = "1" ] && download_tc1
    [ "${ENABLE_TC2:-1}" = "1" ] && download_tc2
    [ "${ENABLE_TC3:-1}" = "1" ] && download_tc3
    [ "${ENABLE_TC4:-1}" = "1" ] && download_tc4
else
    for tc in "${TC_ARGS[@]}"; do
        download_single "$tc"
    done
fi
